version: '3.9'

services:
  db:
    image: postgres:16
    container_name: messenger-db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: messenger_db
    ports:
      - "5433:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d